helm:
  parameters:
  - name: image.name
    value: youngmin1085/user-service
    forcestring: true
  - name: image.tag
    value: dev@sha256:780c1602ca29868fdb0b4adba5a3d30585ee6ae8be81004c46a7fa08570911c0
    forcestring: true
