helm:
  parameters:
  - name: deployment.containers[0].image
    value: youngmin1085/user-service
    forcestring: true
  - name: deployment.containers[0].tag
    value: dev-48372c6
    forcestring: true
