helm:
  parameters:
  - name: image.name
    value: youngmin1085/order-service
    forcestring: true
  - name: image.tag
    value: dev@sha256:ee7683ea17060028c333854013d5c0f5616ef7f0995d92db6bd1ea6d60124ea9
    forcestring: true
