helm:
  parameters:
  - name: image.name
    value: youngmin1085/order-service
    forcestring: true
  - name: image.tag
    value: dev@sha256:d9f8dea18ea76ca3d257c56136ed17b7e5edabeb65437bc91d0110d62a240e79
    forcestring: true
